### ISSUE TITLE
Error in send transaction with Dwolla.

### ISSUE THREAD

**Issue by Sebamax91** [Dwolla/dwolla-ruby#29]
Hi!
We are having problems with the send transaction method under the sandbox platform. After the login in te platform and return to our site, when the user wants to send the amount we get the following error:

There was an error parsing Dwolla's API response: "<Fault xmlns=\"http://schemas.microsoft.com/ws/2005/05/envelope/none\"><Code><Value>Receiver</Value><Subcode><Value xmlns:a=\"http://schemas.microsoft.com/net/2005/12/windowscommunicationfoundation/dispatcher\">a:InternalServiceFault</Value></Subcode></Code><Reason><Text xml:lang=\"en-US\">The server was unable to process the request due to an internal error. For more information about the error, either turn on IncludeExceptionDetailInFaults (either from ServiceBehaviorAttribute or from the &lt;serviceDebug&gt; configuration behavior) on the server in order to send the exception information back to the client, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the server trace logs.</Text></Reason></Fault>" (HTTP response code was 200)

Thanks in advance!

**Comment by mach-kernel** [comment]
No followup - closed.
