### ISSUE TITLE
Should remove rest-client

### ISSUE THREAD

**Issue by aselder** [Dwolla/dwolla-ruby#31]
The dependency on rest-client should be removed. A security vulnerability was discovered in rest client and anyone using bundle-audit will get error if rest-client is used.

See: http://www.osvdb.org/show/osvdb/117461

**Comment by mach-kernel** [comment]
Thanks for bringing this to my attention. I get home later tonight so I'll
take a look then.

David Stancu

@mach-kernel <http://github.com/mach-kernel>

*Dwolla* / Developer Intern

On Feb 17, 2015, at 17:20, Andrew Selder <notifications@github.com> wrote:

The dependency on rest-client should be removed. A security vulnerability
was discovered in rest client and anyone using bundle-audit will get error
if rest-client is used.

See: http://www.osvdb.org/show/osvdb/117461

—
Reply to this email directly or view it on GitHub
<https://github.com/Dwolla/dwolla-ruby/issues/31>.

**Comment by bruschill** [comment]
According to [this commit](https://github.com/rest-client/rest-client/commit/221e3f200f76bd1499591fbc6c3ea3f6183b66ef), removing `rest-client` isn't necessary. The current version specified in the gemspec is 1.4.3, so it just needs to be updated to 1.7.3 or later.

**Comment by mach-kernel** [comment]
Closing the issue, @bruschill is right, I will bump the Gemspec

**Comment by aselder** [comment]
@mach-kernel Is there any reason why the gemspec was updated to ~> 1.7.3, this precludes the latest version of rest-client (1.8.0). Perhaps you wanted "~> 1.7, >= 1.7.3"?
