### ISSUE TITLE
dwolla-Not Redirecting Clients for payment.

### ISSUE THREAD

**Issue by moneygirl1** [Dwolla/dwolla-ruby#34]
Do you have any idea of how I would fix the issue if my site is not redirecting clients for payment using dwolla payment extension?

1. Already remove and re-installed via remote-connecting and mannually.

**Comment by mach-kernel** [comment]
@moneygirl1,

The `dwolla-ruby` gem does not actually process any redirects for URLs that it produces. This is something that is within the scope of your application, but outside of the scope of `dwolla-ruby`. 

Let me know if the gem is providing any inconveniences otherwise I will close this issue by EOD.

**Comment by mach-kernel** [comment]
unrelated

**Comment by moneygirl1** [comment]
Thanks just incase, the solution used to to not use onepage checkout because of "Ajax" and use another one step checkout method.

**Comment by mach-kernel** [comment]
I am glad that everything is working.

Please, in the future, refrain from posting issue requests on unrelated
boards such as this one. This is support for the dwolla-ruby gem, and not
for anything else. While we absolutely love nothing more than helping you,
it is a hindrance on our end to open these requests on unrelated areas and
will only get your problem resolved in a tardier manner.

Thank you for using Dwolla! :)

On Mon, Apr 20, 2015 at 6:08 PM, moneygirl1 <notifications@github.com>
wrote:

> Thanks just incase, the solution used to to not use onepage checkout
> because of "Ajax" and use another one step checkout method.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dwolla/dwolla-ruby/issues/34#issuecomment-94580847>.
>



-- 
David Stancu
@mach-kernel <http://github.com/mach-kernel>
*Dwolla* / Developer Intern
