### ISSUE TITLE
V2

### ISSUE THREAD

**Issue by jackchang** [Dwolla/dwolla-ruby#41]
is this gem going to support v2?

**Comment by mach-kernel** [comment]
This gem will not support V2. All of the V2 SDKs are generated by the
swagger codegen suite and will be versioned together with the API (e.g as
the schema changes)

David Stancu

@mach-kernel <http://github.com/mach-kernel>

*Dwolla* / Developer Relations Engineer

On Oct 9, 2015, at 2:50 PM, Jack Chang <notifications@github.com> wrote:

is this gem going to support v2?

—
Reply to this email directly or view it on GitHub
<https://github.com/Dwolla/dwolla-ruby/issues/41>.

**Comment by jackchang** [comment]
Got it. Thanks
